name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch: # Permite execução manual

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instala Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Instala dependências
        run: npm ci

      - name: Builda o projeto Angular
        run: |
          npm run build:gh-pages
          # Move arquivos da pasta browser se existir (Angular 18+)
          if [ -d "docs/browser" ]; then
            echo "Movendo arquivos da pasta browser para docs..."
            cp -r docs/browser/* docs/
            rm -rf docs/browser
          fi
          # Cria arquivo .nojekyll para desabilitar Jekyll no GitHub Pages
          touch docs/.nojekyll
          # Cria arquivo 404.html para SPA routing
          if [ -f "docs/index.html" ]; then
            cp docs/index.html docs/404.html
          fi
          # Lista arquivos gerados para debug
          echo "Arquivos gerados na pasta docs:"
          ls -la docs/

      - name: Publica no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
